### ISSUE TITLE
Could `from_value` borrow the `JsValue` instead?

### ISSUE THREAD

**Issue by fosskers** [cloudflare/serde-wasm-bindgen#17]
Hi there, I've hit a scenario where I'd like to decode the same `JsValue` a number of times, but it seems that `from_value` wants full ownership of its argument. Is there a technical reason why the arg can't be borrowed instead? For instance, the good ol' `JsValue::into_serde` does borrow its arg.

Cheers and thank you!

**Comment by RReverser** [comment]
It's because deserializer itself needs to hold `JsValue` in various places, and holding borrow would mean introducing extra lifetimes in the APIs as well as dereferencing overhead on all `JsValue` calls (or implicitly cloning when value is passed to the API, which is also not ideal).

Additionally, most usecases just do a one-off conversion to a Rust type and never use original `JsValue` again, so changing the API and adding that overhead would be a net negative for the common case.

That said, note that `JsValue` is essentially just a newtype around an integer (an index to a value on the JS side), that is, by itself, it's as cheap to clone as, say, `Rc<T>`. That means you can call `from_value(js_value.clone())` yourself with basically zero overhead if you want to keep original `JsValue` around.

Does that not cover your usecase?

**Comment by fosskers** [comment]
Wait, so does `JsValue::clone()` do a deep copy on the JS side or anything?

**Comment by RReverser** [comment]
> do a deep copy on the JS side or anything

No, it's literally just increasing refcount to the value, much like if you did `let b = a;` in JS.

**Comment by fosskers** [comment]
Then that should do it for me, thank you!
