### ISSUE TITLE
Serialize Rust Vector to JS typed array (Float32Array, Uint32Array, Uint16Array ...)

### ISSUE THREAD

**Issue by lanceschi** [cloudflare/serde-wasm-bindgen#2]
Hi,

I spent a few time with this great lib although I would like to know if there's a workaround in order to pass back to javascript typed arrays (`Float32Array`, `Uint32Array`, `Uint16Array` ...)?

Something like what is feasible with https://github.com/serde-rs/bytes for Rust `Vec<u8>`.

Thanks!

**Comment by Pauan** [comment]
web-sys already has this functionality built-in:

https://rustwasm.github.io/wasm-bindgen/api/js_sys/struct.Uint8Array.html#impl-From%3C%26%27a%20%5Bu8%5D%3E

(And similarly for the other typed arrays)

Keep in mind this will make a `O(n)` copy of the data.

**Comment by lanceschi** [comment]
Hi @Pauan ,

thanks for reaching out and for the precious tip.

I followed your advice and flicking through docs, [issues](https://github.com/rustwasm/wasm-bindgen/pull/918#issuecomment-445495395) and [reddit threads](https://www.reddit.com/r/rust/comments/a2ljdb/wasm_webgl_why_is_this_pointer_divided_by_4/), I learned a little bit more regarding Rust/Wasm interaction and I ended up successfully using `js_sys::Float32Array` [subarray method](https://rustwasm.github.io/wasm-bindgen/api/js_sys/struct.Float32Array.html#method.subarray).

I got your point regarding `O(n)` classification of data copying function, but we're talking about memory. 
It should be fast enough (correct me if I'm wrong)? Are there better approaches that can implemented instead?

Thanks a lot!

**Comment by Pauan** [comment]
> It should be fast enough (correct me if I'm wrong)?

Yeah, it's probably pretty fast.

> Are there better approaches that can implemented instead?

No, in order to maintain memory safety it has to make a copy.

There is a [`view`](https://rustwasm.github.io/wasm-bindgen/api/js_sys/struct.Uint8Array.html#method.view) function which doesn't do any copying, but it is `unsafe`, so you have to be careful to uphold its guarantees.

In particular, as long as the typed array is alive you must not do any Rust allocations whatsoever. That means no `Vec`, no `Box`, no `String`, etc.

So if you're passing the typed array to JS, and you don't call any Rust functions until after it's been discarded in JS, then yeah you can use it.

But I recommend using the safe `From` impl, because it doesn't have any of those problems.

> flicking through docs, issues and reddit threads

That code is unsafe. It is using the raw WebAssembly memory, which can be invalidated at any time.

It is the same as the `view` function, except that post was made before `view` existed. Nowadays you should [just use `view`](https://github.com/rustwasm/wasm-bindgen/pull/1618/files).

But as I said above, if you use `view` then you need to carefully uphold the memory guarantees. So it's better to use `From` unless you really know what you're doing.

**Comment by lanceschi** [comment]
Hi @Pauan ,

I got your concern regarding unsafe memory guarantees.

I took the time to check [source code](https://rustwasm.github.io/wasm-bindgen/api/src/js_sys/lib.rs.html#4681) and see how the `From trait` was implemented for Rust slices argument. I'll definitely follow your advice!

Thanks again!
