### ISSUE TITLE
ReferenceType integration?

### ISSUE THREAD

**Issue by codefromthecrypt** [cloudflare/serde-wasm-bindgen#35]
Hi, now that there's a draft of WebAssembly 2.0, including reference types, are you planning to employ them here? If not yet, is that pending something in Rust or otherwise? I work on a runtime that supports reference types, but not really found serdes that use it..

**Comment by RReverser** [comment]
Reference types are a lower-level feature, not something exposed to libraries.

wasm-bindgen does support them https://rustwasm.github.io/wasm-bindgen/reference/reference-types.html, so if you enable them via the corresponding flag when invoking wasm-bindgen, the generated code should be able to use reference types instead of custom JS value handling.
