### ISSUE TITLE
Add support for serializing `Closure`s

### ISSUE THREAD

**Issue by mfreeborn** [cloudflare/serde-wasm-bindgen#37]
I've been trying unsuccessfully for a short while to see if I can serialize a `wasm_bindgen::closure::Closure` (or `js_sys::Function`?), and I wonder if it is possible?

Essentially I'm trying to expose a Rust struct on which the user can set various parameters - some of which are callback functions - and I would like to be able to be able to serialize that that and pass it to the JavaScript side.

**Comment by RReverser** [comment]
This would be a subcase of #32, with implementation as described in https://github.com/cloudflare/serde-wasm-bindgen/issues/32#issuecomment-1016466190 working for any wasm-bindgen types, including `js_sys::Function`. I'll close this issue in favour of the other one and would welcome a PR.

Alternatively, you could just expose your Rust struct via `#[wasm_bindgen]` mechanism instead of serializing.
