### ISSUE TITLE
Internally tagged enumerations cannot deserialize byte buffers

### ISSUE THREAD

**Issue by reknih** [cloudflare/serde-wasm-bindgen#38]
When deserializing a `JsValue` to an enum that is [internally tagged](https://serde.rs/enum-representations.html#internally-tagged) within JavaScript, `serve_bytes::ByteBuf`s produce errors:

- When the JavaScript value is a `Uint8Array`, the deserialization fails with the error `invalid type: any, expected byte array`.
- When the value is an `ArrayBuffer`, the deserialization fails with the error `invalid type: map, expected byte array`.

When the `#[serde(tag = "type")]` is removed, and externally tagged enums are passed, the serialization works for both input types. Below, you can check out a code example for the bug:

```rust
#[derive(Debug, Deserialize)]
#[serde(tag = "type")]
enum MyEnum {
    Buffer { buffer: serde_bytes::ByteBuf },
    Text { text: String },
}

#[wasm_bindgen]
pub fn echo(val: JsValue) {
    web_sys::console::log_1(&val);
    let des: MyEnum = serde_wasm_bindgen::from_value(val).unwrap();
    log::trace!("{:?}", des);
}
```

The JavaScript representation of `MyEnum` shall look as defined below:
```typescript
type MyEnum = 
  | {type: "Buffer"; buffer: Uint8Array | ArrayBuffer}
  | {type: "Text"; text: string}
```

**Comment by RReverser** [comment]
Does this work for deserialization from JSON?

Generally, serde has a lot of problems with internally tagged enums, because it first deserializes them into an internal "fat" container with all kinds of data, and then tries to convert from that into the destination format.

The problem with that approach is that, of course, only types that serde hardcoded in its internal representation are supported, while more esoteric ones - likely, including byte buffers - are not.

See https://github.com/serde-rs/serde/issues/1183 for more details.

**Comment by RReverser** [comment]
I'm going to close this as I'm fairly sure this is the linked upstream issue and not something we can fix on our side.
