### ISSUE TITLE
Error is not compatible with `Sync`/`Send`/`anyhow::Error`

### ISSUE THREAD

**Issue by regexident** [cloudflare/serde-wasm-bindgen#42]
While trying to move away from `wasm-bindgen`'s deprecated `JsValue::from_serde`/`JsValue::into_serde` via `serde-wasm-bindgen` in an async-heavy codebase I found that the fact that `serde_wasm_bindgen::Error` stores a `JsValue`, which in turn stores a `marker::PhantomData<*mut u8>` ([code](https://github.com/rustwasm/wasm-bindgen/blob/d090e94512c87cc2495d1491a79d8bdc500074d3/src/lib.rs#L94)) effectively prevents the use with `anyhow` or any other code that constrains its errors by `std::error::Error + Send + Sync + 'static`. Especially async code tends to require error types to be `Send + Sync`.

Having had a glance over the implementation I would assume that the internal `JsValue` field of `serde_wasm_bindgen::Error` could be replaced with a `Send + Sync` representation (e.g. a plain old `String`). The `From<Error> for JsValue` implementation would then perform the conversion to `JsValue` dynamically.

The current reliance on `JsValue` can also be somewhat annoying in situations where you're performing a serde->wasm conversion, but on failure need to present/handle the error in Rust, rather than JS. A `JsValue`-based error is of little use here. Having a non-`JsValue` internal representation would also improve this use-case.

Merely the implementation of `From<JsValue> for Error` ([code](https://github.com/cloudflare/serde-wasm-bindgen/blob/master/src/error.rs#L42-L46)) would have to either be replaced with `TryFrom<JsValue>` (since a `JsValue` could contain a non-string value) or replace the current `Error(error)` with something like `Error(error.as_string().expect("error message"))`.

Would you be open for a PR that makes these changes?

**Comment by RReverser** [comment]
In general, JsError / JsValue-based error is more useful in Wasm-related code because it creates a JS error with `.stack` correctly tracked by the JS engine and associated with the original thrown location. Rust backtraces can't provide that level of detail in Wasm, so creating errors from string at the last stage makes them much less useful for actual debugging.

That's why I prefer to do the opposite and convert JsError to string only when I really want to go from JS error to a Rust error and I'm okay with stripping the backtrace.

Most of the time, you also use serde-wasm-bindgen at the top level of the function exposed via `#[wasm_bindgen]` anyway, so as long as you're propagating it immediately to `Result<..., JsValue>`, the fact that JS values are not thread-safe shouldn't be a problem.

I wonder what your usecase is where this doesn't work.

**Comment by regexident** [comment]
> In general, JsError / JsValue-based error is more useful in Wasm-related code because it creates a JS error with `.stack` correctly tracked by the JS engine and associated with the original thrown location inside Wasm. Rust backtraces can't provide that level of detail in Wasm, so creating errors from string at the last stage makes them much less useful for actual debugging.

That does indeed make a lot of sense!

I'm working on a cross-platform project that among several native targets also supports the web via wasm.

We're basically wrapping individual errors into a wrapper-`enum` error type in order to provide more fine-grained internal error-handling via `thiserror`.

It looks like I managed to make things work with this change:

Before:
```rust
#[derive(Debug, Error)]
pub enum MyError {
    SerdeWasmBindgen(Box<dyn std::error::Error + Send>),
    // ...
}

#[cfg(not(target_arch = "wasm32"))]
unsafe impl Send for MyError {}
```

After:
```rust
#[cfg(target_arch = "wasm32")]
type BoxedStdError = Box<dyn std::error::Error>;

#[cfg(not(target_arch = "wasm32"))]
type BoxedStdError = Box<dyn std::error::Error + Send>;

#[derive(Debug, Error)]
pub enum MyError {
    SerdeWasmBindgen(BoxedStdError),
    // ...
}

#[cfg(not(target_arch = "wasm32"))]
unsafe impl Send for MyError {}
```

**Comment by RReverser** [comment]
That looks reasonable, although note that `Box<dyn std::error::Error>` will be still prone to the same problem with erased backtrace (since it's an erased generic Rust error type).

Maybe store actual `serde_wasm_bindgen::Error` there instead?

Also note that you can use `cfg` on enum branches so the whole thing might be simplified to:

```rust
#[derive(Debug, Error)]
pub enum MyError {
	#[cfg(target_arch = "wasm32")]
    SerdeWasmBindgen(serde_wasm_bindgen::Error),
    // ...regular errors
}
```

This should also let Rust automatically implement `Send` on your error enum when possible (non-wasm32 targets), and `!Send` when not (wasm32) instead of you overriding it via manual `unsafe impl`.
