### ISSUE TITLE
as_bytes() does not work if self is an Array

### ISSUE THREAD

**Issue by bhalleycf** [cloudflare/serde-wasm-bindgen#43]
In [workers-rs:284](https://github.com/cloudflare/workers-rs/issues/284) we have a problem converting JSON of a tuple struct's content.  The tuple struct has its own deserialize method, which calls deserialize_bytes().  The thing it calls deserialize_bytes() on looks like

```
JsValue([230, 114, 9, 67, 96, 183, 184, 19, 98, 50, 100, 228, 98, 181, 82, 4])
```

But as_bytes() handles only Uint8Array and ArrayBuffer, not Array, and so it fails to convert and deserialization fails.  If I make the following change, things work:

```
diff --git a/src/de.rs b/src/de.rs
index 6322045..7a6e7db 100644
--- a/src/de.rs
+++ b/src/de.rs
@@ -175,6 +175,9 @@ impl Deserializer {
         } else if let Some(v) = self.value.dyn_ref::<ArrayBuffer>() {
             temp = Uint8Array::new(v);
             &temp
+        } else if let Some(v) = self.value.dyn_ref::<Array>() {
+            temp = Uint8Array::new(v);
+            &temp
         } else {
             return None;
         };
```

AFAIK there is nothing wrong with what the caller is doing and supporting Array as well seems reasonable, but I am no expert in this area!

**Comment by RReverser** [comment]
That's right, `deserialize_bytes` is intended for serializers/deserializers that have special optimised representation for byte blobs - in our case, ArrayBuffer / Uint8Array - and not as a replacement for general arrays.

The conversion you're showing in your diff is lossy and would silently ignore any invalid items in an array by converting them into numbers according to JS casting rules.

If you don't have control over the JS values - ideally it should be a `Uint8Array` in the first place - then the best thing to do is annotate the data structure with custom `#[serde(deserialize_with = ...)` that deserializes data as a regular `Vec<u8>` instead of going via `deserialize_bytes`. This would deserialize it as any other array and perform all the necessary checks.

**Comment by bhalleycf** [comment]
Thank you for the speedy response.  We do not have control over the JS values in this case, so I will try the annotations you suggest.

**Comment by RReverser** [comment]
Thinking about this a bit more, given that we even have a JSON-compatible mode in serializer, we probably should support Array sources anyway. That will have to be implemented a bit differently though - instead of converting to `Uint8Array`, which, as mentioned above, would be lossy - instead it should go via `visit_seq` like it does in the `deserialize_seq` branch.

Things like `serde_bytes::ByteBuf` can already handle `visit_seq` correctly alongside the `visit_bytes`, and will do their own checks while walking through the sequence.

I don't know if I'll have time to implement this, but PRs are welcome.
