### ISSUE TITLE
Produce Object instead of Map when converting to JsValue

### ISSUE THREAD

**Issue by hamza1311** [cloudflare/serde-wasm-bindgen#49]
`serde_wasm_bindgen::to_value` returns `Map`. It should return an `Object`, as that's what's wanted quite often.

The following function, when called, should return the same output as it's input:
```rust
fn identity(value: JsValue) -> Result<JsValue, Error> {
    let value: serde_json::Value = serde_wasm_bindgen::from_value(value)?;
    serde_wasm_bindgen::to_value(value)
}
```
However that is not the case.

There should at least be a way to configure what is returned.

**Additional Details**:
This came up because I'm writing a JS library that uses [`json_patch`](https://docs.rs/json-patch/).  More specifically, the following snippet:
```
let mut doc = serde_wasm_bindgen::from_value(doc)?;
let patches: Vec<PatchOperation> = serde_wasm_bindgen::from_value(patches)?;
json_patch::patch(&mut doc, &patches)?
serde_wasm_bindgen::to_value(&doc)
```
When passed with objects, after manipulation, it returns `Map`s, which is undesirable.

**Comment by RReverser** [comment]
Also note that Map is returned only for Rust HashMaps, BTreeMaps and so on, as it should be. Plain structs already default to returning objects.

One exception is if you use `serde(flatten)` which is historically problematic in Serde precisely because it loses type information and turns e.g. objects into maps.

You didn't show your data structures, only the general serialization code, so I'm only guessing here but if you use `serde(flatten)`, that might be why you're getting Maps by default.
